### ISSUE TITLE
When having stored something like image data in clipboard, the application slows down.

### ISSUE THREAD

**Issue by SSBMTonberry** [SSBMTonberry/emu-jukebox#27]
To reproduce, simply make a GIMP project with a 16x16 image, color those pixels, then select them all and copy. Then open Emu-Jukebox, and witness that it becomes VERY slow.

**Comment by AlexanderBrevig** [comment]
NOT REPRODUCIBLE ON WINDOWS

The SFML lib is very spammy but the app runs just fine.
I had a look at the Linux implementation though, seems to wait a second for a response from X during a conversion request.
https://github.com/SSBMTonberry/emu-jukebox/blob/master/external_libs/source/SFML/Window/Unix/ClipboardImpl.cpp#L149

Does emu-jukebox really need to rely on the clipboard though? Only reference I found for the clipbard was in the CodeEditor component (which I don't think really is in use?).

Maybe simply remove the ClipboardManager, or make it pollable instead of self-updating?

**Comment by SSBMTonberry** [comment]
Thanks for looking at the issue! It is very likely a Linux/X11 thing. While the ClipboardManager is not used a lot in this project, it is an essensial feature in a few scenarios. Nevertheless, I'm using the same ClipboardManager much more in another project that is still not "ready for the public", and simply removing it is not solving the issue, that will be a breaking problem in the other project.

I am however VERY positive to improvements! As it is now, it is very simple, and has very likely not been designed to handle a few cases, like this one. As long as it is able to do its job, I'm happy! The main job for the ClipboardManager is to sync the clipboard between ImGui and the OS (in both directions).

SFML's clipboard handling has had some critical flaws in the past, so I am not surprised if there is a flaw in their implemtation for Linux that is causing it (as well as maybe a flawed ClipboardManager on my side). Also, it already spams the console when it finds something that is not Unicode, which I think is BAD (I have a separate issue on that one: #19).

**Comment by SSBMTonberry** [comment]
Now uses polling logic and hotkeys to activate the clipboard.
Tested with a 1920x1080 pixels image in the clipboard. The result is a "hang" for 1 sec, then the application is running all fine again. I would say this fixes the problem, as what I experience now is not something I consider an issue.
